Rendering issue
maxspahn/gym_envs_planar pull request #7
Opened 2021-11-09 14:19 UTC by alxschwrz

Added rendering option for all examples and environments as described in issue #3

2021-11-13 08:26 UTC, maxspahn requested changes
Nice work. Could you remove the commented lines with env.render(). So that it is clean.

2021-11-13 08:26 UTC, maxspahn commented on examples/ground_robot.py
> +            #env.render()
You can actually remove that line entirely.

2021-11-13 08:26 UTC, maxspahn commented on examples/ground_robot_arm.py
> +            #env.render()
Remove

2021-11-15 07:53 UTC, alxschwrz commented
Thanks. I deleted the deprecated render calls in ground_robot.py and ground_robot_arm.py in commit fc23dfbff18e4c93401653384a93421c133a1b10.

2021-11-15 08:54 UTC, maxspahn approved these changes

2021-11-15 08:55 UTC, merged